<?php
$data = array (
  528 => 
  array (
    'cat_id' => '528',
    'cat_name' => '限时特卖',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'type_img' => NULL,
    'goods_num' => 114,
    'level' => 0,
    'id' => '528',
    'name' => '限时特卖',
  ),
  596 => 
  array (
    'cat_id' => '596',
    'cat_name' => '美国加州宝宝',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '6',
    'level' => 1,
    'id' => '596',
    'name' => '美国加州宝宝',
  ),
  587 => 
  array (
    'cat_id' => '587',
    'cat_name' => '美国进口产品',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '3',
    'level' => 1,
    'id' => '587',
    'name' => '美国进口产品',
  ),
  595 => 
  array (
    'cat_id' => '595',
    'cat_name' => '新西兰面膜',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '1',
    'level' => 1,
    'id' => '595',
    'name' => '新西兰面膜',
  ),
  597 => 
  array (
    'cat_id' => '597',
    'cat_name' => '禧贝happy',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
    'level' => 1,
    'id' => '597',
    'name' => '禧贝happy',
  ),
  586 => 
  array (
    'cat_id' => '586',
    'cat_name' => '嘉宝辅食',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '11',
    'level' => 1,
    'id' => '586',
    'name' => '嘉宝辅食',
  ),
  600 => 
  array (
    'cat_id' => '600',
    'cat_name' => '德国禧宝hipp',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '7',
    'level' => 1,
    'id' => '600',
    'name' => '德国禧宝hipp',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '母婴专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '12',
    'type_img' => '',
    'goods_num' => 10,
    'level' => 0,
    'id' => '22',
    'name' => '母婴专区',
  ),
  486 => 
  array (
    'cat_id' => '486',
    'cat_name' => '荷兰本土牛栏',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '5',
    'level' => 1,
    'id' => '486',
    'name' => '荷兰本土牛栏',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'Aptamil铂金',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '4',
    'level' => 1,
    'id' => '52',
    'name' => 'Aptamil铂金',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Aptamil金装',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '4',
    'level' => 1,
    'id' => '55',
    'name' => 'Aptamil金装',
  ),
  485 => 
  array (
    'cat_id' => '485',
    'cat_name' => 'a2白金奶粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '3',
    'level' => 1,
    'id' => '485',
    'name' => 'a2白金奶粉',
  ),
  483 => 
  array (
    'cat_id' => '483',
    'cat_name' => '贝拉米奶粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 4,
    'level' => 1,
    'id' => '483',
    'name' => '贝拉米奶粉',
  ),
  484 => 
  array (
    'cat_id' => '484',
    'cat_name' => '可瑞康普通装',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '2',
    'level' => 1,
    'id' => '484',
    'name' => '可瑞康普通装',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '可瑞康羊奶粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '2',
    'level' => 1,
    'id' => '56',
    'name' => '可瑞康羊奶粉',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '尿不湿 纸尿裤',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '24',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 17,
    'level' => 1,
    'id' => '18',
    'name' => '尿不湿 纸尿裤',
  ),
  523 => 
  array (
    'cat_id' => '523',
    'cat_name' => 'Baby米粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '36',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '18',
    'level' => 1,
    'id' => '523',
    'name' => 'Baby米粉',
  ),
  598 => 
  array (
    'cat_id' => '598',
    'cat_name' => '英国Aptamil',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
    'level' => 1,
    'id' => '598',
    'name' => '英国Aptamil',
  ),
  599 => 
  array (
    'cat_id' => '599',
    'cat_name' => '英国牛栏Cow',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
    'level' => 1,
    'id' => '599',
    'name' => '英国牛栏Cow',
  ),
  579 => 
  array (
    'cat_id' => '579',
    'cat_name' => '德国爱他美',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '6',
    'level' => 1,
    'id' => '579',
    'name' => '德国爱他美',
  ),
  527 => 
  array (
    'cat_id' => '527',
    'cat_name' => '营养保健',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '7',
    'type_img' => NULL,
    'goods_num' => 47,
    'level' => 0,
    'id' => '527',
    'name' => '营养保健',
  ),
  568 => 
  array (
    'cat_id' => '568',
    'cat_name' => '美容养颜',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '5',
    'level' => 1,
    'id' => '568',
    'name' => '美容养颜',
  ),
  569 => 
  array (
    'cat_id' => '569',
    'cat_name' => '健康內调',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 3,
    'level' => 1,
    'id' => '569',
    'name' => '健康內调',
  ),
  570 => 
  array (
    'cat_id' => '570',
    'cat_name' => '孕妇营养',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '6',
    'level' => 1,
    'id' => '570',
    'name' => '孕妇营养',
  ),
  571 => 
  array (
    'cat_id' => '571',
    'cat_name' => '预防三高',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
    'level' => 1,
    'id' => '571',
    'name' => '预防三高',
  ),
  573 => 
  array (
    'cat_id' => '573',
    'cat_name' => '心脑保健',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 7,
    'level' => 1,
    'id' => '573',
    'name' => '心脑保健',
  ),
  574 => 
  array (
    'cat_id' => '574',
    'cat_name' => '关节养护',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 6,
    'level' => 1,
    'id' => '574',
    'name' => '关节养护',
  ),
  575 => 
  array (
    'cat_id' => '575',
    'cat_name' => '增强体质',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 16,
    'level' => 1,
    'id' => '575',
    'name' => '增强体质',
  ),
  576 => 
  array (
    'cat_id' => '576',
    'cat_name' => '进口美食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '17',
    'level' => 0,
    'id' => '576',
    'name' => '进口美食',
  ),
  529 => 
  array (
    'cat_id' => '529',
    'cat_name' => '日化用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '12',
    'level' => 0,
    'id' => '529',
    'name' => '日化用品',
  ),
  566 => 
  array (
    'cat_id' => '566',
    'cat_name' => 'wait......',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '206',
    'level' => 0,
    'id' => '566',
    'name' => 'wait......',
  ),
  601 => 
  array (
    'cat_id' => '601',
    'cat_name' => 'a2成人奶粉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '1',
    'level' => 0,
    'id' => '601',
    'name' => 'a2成人奶粉',
  ),
);
?>