<?php
$data = array (
  0 => 
  array (
    'cat_id' => '528',
    'cat_name' => '限时特卖',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'type_img' => NULL,
    'goods_num' => 114,
  ),
  1 => 
  array (
    'cat_id' => '22',
    'cat_name' => '母婴专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '12',
    'type_img' => '',
    'goods_num' => 10,
  ),
  2 => 
  array (
    'cat_id' => '527',
    'cat_name' => '营养保健',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '7',
    'type_img' => NULL,
    'goods_num' => 47,
  ),
  3 => 
  array (
    'cat_id' => '576',
    'cat_name' => '进口美食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '17',
  ),
  4 => 
  array (
    'cat_id' => '529',
    'cat_name' => '日化用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '12',
  ),
  5 => 
  array (
    'cat_id' => '566',
    'cat_name' => 'wait......',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '206',
  ),
  6 => 
  array (
    'cat_id' => '601',
    'cat_name' => 'a2成人奶粉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '486',
    'cat_name' => '荷兰本土牛栏',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '5',
  ),
  8 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'Aptamil铂金',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '4',
  ),
  9 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Aptamil金装',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '4',
  ),
  10 => 
  array (
    'cat_id' => '485',
    'cat_name' => 'a2白金奶粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '3',
  ),
  11 => 
  array (
    'cat_id' => '483',
    'cat_name' => '贝拉米奶粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 4,
  ),
  12 => 
  array (
    'cat_id' => '484',
    'cat_name' => '可瑞康普通装',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '2',
  ),
  13 => 
  array (
    'cat_id' => '56',
    'cat_name' => '可瑞康羊奶粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => '2',
  ),
  14 => 
  array (
    'cat_id' => '18',
    'cat_name' => '尿不湿 纸尿裤',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '24',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 17,
  ),
  15 => 
  array (
    'cat_id' => '523',
    'cat_name' => 'Baby米粉',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '36',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '18',
  ),
  16 => 
  array (
    'cat_id' => '598',
    'cat_name' => '英国Aptamil',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
  ),
  17 => 
  array (
    'cat_id' => '599',
    'cat_name' => '英国牛栏Cow',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
  ),
  18 => 
  array (
    'cat_id' => '579',
    'cat_name' => '德国爱他美',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '6',
  ),
  19 => 
  array (
    'cat_id' => '568',
    'cat_name' => '美容养颜',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '5',
  ),
  20 => 
  array (
    'cat_id' => '569',
    'cat_name' => '健康內调',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 3,
  ),
  21 => 
  array (
    'cat_id' => '570',
    'cat_name' => '孕妇营养',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '6',
  ),
  22 => 
  array (
    'cat_id' => '571',
    'cat_name' => '预防三高',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
  ),
  23 => 
  array (
    'cat_id' => '573',
    'cat_name' => '心脑保健',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 7,
  ),
  24 => 
  array (
    'cat_id' => '574',
    'cat_name' => '关节养护',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 6,
  ),
  25 => 
  array (
    'cat_id' => '575',
    'cat_name' => '增强体质',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => 16,
  ),
  26 => 
  array (
    'cat_id' => '596',
    'cat_name' => '美国加州宝宝',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '6',
  ),
  27 => 
  array (
    'cat_id' => '587',
    'cat_name' => '美国进口产品',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '3',
  ),
  28 => 
  array (
    'cat_id' => '595',
    'cat_name' => '新西兰面膜',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '1',
  ),
  29 => 
  array (
    'cat_id' => '597',
    'cat_name' => '禧贝happy',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '4',
  ),
  30 => 
  array (
    'cat_id' => '586',
    'cat_name' => '嘉宝辅食',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '11',
  ),
  31 => 
  array (
    'cat_id' => '600',
    'cat_name' => '德国禧宝hipp',
    'measure_unit' => '',
    'parent_id' => '528',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => NULL,
    'goods_num' => '7',
  ),
);
?>